### ISSUE TITLE
Remove hard-coded aliases

### ISSUE THREAD

**Issue by yardstick17** [shubhamchaudhary/dotfiles#19]
https://github.com/ylogx/dotfiles/blob/6a69075fc678a7751d0565fe26883ba0e8c66dd2/home/.dev_aliases.sh#L3-L5

@aktech , @suheb Individual Productivity is hampered!!

**Comment by ylogx** [comment]
Thanks for bringing these up. 
These were old aliases for going directly into dev environment from the Season of KDE time. Now a days there are much better utilities like [autojump](https://github.com/wting/autojump).

**Comment by ylogx** [comment]
@yardstick17 I removed [a](https://github.com/ylogx/dotfiles/commit/f0df3ad3cf0d6b0a78d62ca6513c7b85f8e6fef4) bunch [of](https://github.com/ylogx/dotfiles/commit/0adb7b3f463b1c4ec7cf7e05271098de8cddd1a7) hard-coded stuff. You can [update dotfiles](https://github.com/ylogx/dotfiles#updating-dotfiles) using `hs pull`.

Other than the fact that these are not generic, is there any other issue (like the alias itself messing some autocompletion)? Just confirming the problem.
